export const NavItems = [
    {
        title:"HOME",
        url:"/",
        cName:"nav-links"
    },
    {
        title:"SOLUTION",
        url:"/solution",
        cName:"nav-links"
    },
    {
        title:"ABOUT",
        url:"/about",
        cName:"nav-links"
    },
    {
        title:"CONTACT",
        url:"/contact",
        cName:"nav-links"
    }
]
